### ISSUE TITLE
File size error

### ISSUE THREAD

**Issue by the-wat** [hpsb/schoolBlog#1]
So I uploaded an image for the blog and in the console, it said: "Failed to load resource: the server responded with a status of 413(Request Entity Too Large)".

**Comment by the-wat** [comment]
![Annotation 2020-08-31 131701](https://user-images.githubusercontent.com/69153476/91695805-514a6400-eb8c-11ea-87bc-5d2c7473d6ec.jpg)
![unknown](https://user-images.githubusercontent.com/69153476/91695862-67f0bb00-eb8c-11ea-9602-4165030dbb82.png)
![unknown (1)](https://user-images.githubusercontent.com/69153476/91695906-763ed700-eb8c-11ea-8017-f3f63055d112.png)

**Comment by udbhav-s** [comment]
Fixed, should allow files up to 30MB now.
